version: '3.8'

services:
    frontend:
      build:
        context: example-frontend
        dockerfile: dockerfile
      volumes:
        - .\example-frontend:\example-frontend\usr\src\app
      container_name: cont_frontend
      ports:
        - 5000:5000
    redis:
      image: redis
      ports:
        - 6379:6379
    backend:
      build:
        context: example-backend
        dockerfile: dockerfile
      volumes:
        - .\example-backend:\example-backend\usr\src\app
      container_name: cont_backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis

      